### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by jpaganini** [Shamir-Lab/SCAPP#16]
Hi guys,

how are you? I hope this message finds you well.

I would like to ask you a quick question with respect to the output provided by SCAPP. Every sequence in the multi-FASTA file 'output'_confident_cycs.fasta is predicted to be an 'individual' plasmid?

Thanks for your help!

Cheers,

**Comment by dpellow** [comment]
Yes, that is correct, each sequence in the output file is a complete plasmid 'genome'.
Note that there may be multiple plasmids that share segments of similar sequence, or even plasmid 'strains' that are very similar along their entire length.

**Comment by jpaganini** [comment]
Thanks for your prompt reply. It is very clear to me now.

One more question. Have you tried your tool for predicting plasmids in WGS data rather than in metagenomes? If so, are there any recommended settings?

Thanks again for your time and help!

Cheers,

**Comment by dpellow** [comment]
SCAPP is designed for metagenomic samples, but it should work with default settings in isolate samples.
However, note that in isolates, simplifying assumptions could be made about the coverage of the bacterial chromosome vs the plasmid that make the problem simpler. Since SCAPP doesn't use these assumptions it's possible that other tools such as Recycler or plasmid spades will perform better. We have not benchmarked SCAPP in comparison to those tools on isolate WGS.
I believe SCAPP should perform adequately on isolate WGS, if you do try it out, let us know how it goes.

**Comment by jpaganini** [comment]
Thanks again for the quick reply!

I understand perfectly. I will keep you updated when I try it!

Cheers,
